repos:
  - repo: local
    hooks:
      - id: c-clang-format
        name: "[c]        clang-format"
        entry: clang-format -i
        args: ["-style=file"]
        language: system
        types_or: [c++, c, c#, cuda, java, javascript, json, objective-c, proto, textproto, metal]
      - id: nix-nixpkgs-fmt
        name: "[nix]      nixpkgs-fmt"
        entry: nixpkgs-fmt
        language: system
        files: &nix-files \.nix$
      - id: shell-shellcheck
        name: "[shell]    shellcheck"
        entry: shellcheck --exclude=SC1071,SC1090,SC1091
        language: system
        types: [shell]
      - id: statix
        name: "[nix]      statix"
        entry: statix fix
        language: system
        files: *nix-files
        pass_filenames: false
      - id: yamlfmt
        name: "[yaml]     yamlfmt"
        entry: yamlfmt
        language: system
        types: [yaml]
