#!/usr/bin/env sh

yabai -m rule --add app=Emacs manage=on

yabai -m config debug_output on

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

yabai -m config window_border                off
yabai -m config window_border_width          2
yabai -m config normal_window_border_color   0xff0E86D4
yabai -m config active_window_border_color   0xffF26DF9
yabai -m config insert_feedback_color        0xff0E86D4

yabai -m config layout                       bsp
yabai -m config top_padding                  4
yabai -m config bottom_padding               4
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   4